### PR TITLE
display_area_basic

### PR DESCRIPTION
**Pull request by suresach**
I have added a basic version to show submitted ideas, it still needs to be more comprehensive like showing images/link uploaded by user.

Keep pushing in the suggestions to make things better :)

### CODE REVIEW

**Comment by charmaine** [comment]
@suresach Thank you so much for communicating with me through your process and it looks absolutely lovely! I really appreciate your contribution! 👍

**Comment by suresach** [comment]
yeah!..that's so good!
also, why did you remove that drawing board? ..it was pretty good!

**Comment by charmaine** [comment]
@suresach Oh no! I loved the drawing board!! I think I must have accidentally deleted it while merging conflicts. I'll fix that asap, thank you for the heads up!

**Comment by charmaine** [comment]
@suresach Fixed it. I accidentally messed the index.html file up but it should be all good now! :)

**Comment by suresach** [comment]
yeah..I merged my branch with master! :)

**Pull request merged**
